### ISSUE TITLE
Update jsDelivr links.

### ISSUE THREAD

**Issue by LeeWannacott** [LeeWannacott/table-sort-js#100]
https://cdn.jsdelivr.net/npm/table-sort-js@latest/table-sort.js doesn't seem to show latest version where as https://cdn.jsdelivr.net/npm/table-sort-js@1/table-sort.js seems to actually show the latest released version. Might as well update to this; don't expect to be v2 anytime soon anyway...

update readme and docs links

**Comment by Cioraz** [comment]
Hello, I am interested in contributing could you assign me the issue?

**Comment by LeeWannacott** [comment]
@Cioraz Sure thing you are assigned the issue! (if you could research @latest vs 1 and what it does that might be handy; it doesn't work how I thought it would... I guess because it gets cached, or something...)

**Comment by LeeWannacott** [comment]
Made a related issue for adding another example: using script tag from cdn/jsDelivr: https://github.com/LeeWannacott/table-sort-js/issues/105

**Comment by Cioraz** [comment]
> @Cioraz Sure thing you are assigned the issue! (if you could research @latest vs 1 and what it does that might be handy; it doesn't work how I thought it would... I guess because it gets cached, or something...). I thought it would just give you the latest release?

Hello, I found that when @latest is added, it get cached for 24hrs. So even with new releases within that period, it would still show the same previous version.
Also this is not recommended for production usage as requesting latest usually come with breaking changes which may break the codeflow.

However without the @latest, it loads the newest version immediately whose caching period is 1 week. 

Reference : https://stackoverflow.com/questions/69148904/difference-in-jsdelivr-url-with-without-latest

**Comment by LeeWannacott** [comment]
> > @Cioraz Sure thing you are assigned the issue! (if you could research @latest vs 1 and what it does that might be handy; it doesn't work how I thought it would... I guess because it gets cached, or something...). I thought it would just give you the latest release?
> 
> Hello, I found that when @latest is added, it get cached for 24hrs. So even with new releases within that period, it would still show the same previous version. Also this is not recommended for production usage as requesting latest usually come with breaking changes which may break the codeflow.
> 
> However without the @latest, it loads the newest version immediately whose caching period is 1 week.
> 
> Reference : https://stackoverflow.com/questions/69148904/difference-in-jsdelivr-url-with-without-latest

Okay cool, I think @1 should be good.

**Comment by LeeWannacott** [comment]
@Cioraz Sorry, After thinking about this maybe we can just do https://cdn.jsdelivr.net/npm/table-sort-js/table-sort.js and https://cdn.jsdelivr.net/npm/table-sort-js/table-sort.min.js we don't need @1

**Comment by LeeWannacott** [comment]
Done in PR: https://github.com/LeeWannacott/table-sort-js/pull/107
