### ISSUE TITLE
Glyphs used for table-arrows are rather heavy

### ISSUE THREAD

**Issue by mvl22** [LeeWannacott/table-sort-js#122]
Thanks for this excellent library.

The glyphs used for the table-arrows mode are rather heavy. Possible replacements are:

↑ U+2191 : UPWARDS ARROW
↓ U+2193 : DOWNWARDS ARROW

which I think are quite elegant. Or, closer to the current ones but smaller and so less dominant:

▵ U+25B5 : WHITE UP-POINTING SMALL TRIANGLE
▿ U+25BF : WHITE DOWN-POINTING SMALL TRIANGLE

The latter are probably closer to today's UI expectations for sortable columns.

**Comment by LeeWannacott** [comment]
Yeah they are pretty heavy; I agree. Those look like good replacements. Also the option for the user to be able to set their own could also be cool, then they can use rockets instead of arrows :rocket:

**Comment by mvl22** [comment]
> Yeah, I mean you are not wrong, they are pretty heavy. Those look like good replacements. Also the option for the user to be able to set their own could also be cool, then they can use rockets instead of arrows 🚀

Yes, though it would be good to avoid a new feature delaying sorting out the heaviness.

Setting own icon could be done via a data attribute, e.g. `data-ts-icon="🚀"` on the table.

**Comment by LeeWannacott** [comment]
> ↑ U+2191 : UPWARDS ARROW
> ↓ U+2193 : DOWNWARDS ARROW

I went with these because they matched with `2195 ↕ Up Down Arrow` better.

**Comment by mvl22** [comment]
That looks great, well done :)
