### ISSUE TITLE
Write more tests.

### ISSUE THREAD

**Issue by LeeWannacott** [LeeWannacott/table-sort-js#21]
Write more tests for sorting; that don't already exist..

Install: First clone repository and run `npm install`
Run tests using: `npm run test`
Write tests in: https://github.com/LeeWannacott/table-sort-js/blob/master/test/table.test.js

**Comment by aliosman21** [comment]
I created a pull request for adding more tests kindly review it whenever it's convenient for you

**Comment by LeeWannacott** [comment]
All-right Thanks! I'll check it out. :mag:
