### ISSUE TITLE
Run a minifier over code.

### ISSUE THREAD

**Issue by LeeWannacott** [LeeWannacott/table-sort-js#29]
Run a minifier over shipped code. Setup GitHub workflow to minify table-sort.js.

**Comment by robertlove** [comment]
You could point people to this (it's minified) https://cdn.jsdelivr.net/npm/table-sort-js

**Comment by LeeWannacott** [comment]
Sounds like an option; I would need to look a bit more into. Thanks for the suggestion.

**Comment by LeeWannacott** [comment]
Added a link in the Readme.md to a minified version that comes from: https://cdn.jsdelivr.net/npm/table-sort-js . Thank you!
