### ISSUE TITLE
Test that npm package works with React, Vue and Angular.

### ISSUE THREAD

**Issue by LeeWannacott** [LeeWannacott/table-sort-js#32]
Test that npm package works with React, Vue and Angular.

**Comment by haiderali171** [comment]
@LeeWannacott  I does work with Vue!

**Comment by LeeWannacott** [comment]
@haiderali171 . Yeah it does, I wasn't sure when I opened the issue. Idealistically you would setup automated testing in a browser for the frameworks, to ensure that they keep working. But automated testing is more time intensive than unit tests that are currently setup.
