### ISSUE TITLE
Sort by data-attribute

### ISSUE THREAD

**Issue by fisherspoon** [LeeWannacott/table-sort-js#45]
Hi, your library can sort by dates, but my date format is (02.19.2020)
Therefore, I would suggest adding the ability to sort by date attribute in which you can, for example, put time in milliseconds

**Comment by LeeWannacott** [comment]
Hey,  I have seen some other libraries using data-attributes and I considered it early on; I try to have as much out of the box as possible, however, I should add this for any sorting edge case the library doesn't sort. I would want to make it as generalisable as possible, so the user can put anything they want after data (not just data-dates) assuming its consistent.

**Comment by LeeWannacott** [comment]
Added in commit: ee8e7b952c5008cd36d8f4dd059d782a28825b65 . Users can now use <th class="data-sort">  and use <td data-sort=""> to sort by data-attribute rather than the values of the tables column clicked on. Thanks.
