### ISSUE TITLE
Only the <td> and their values are moved

### ISSUE THREAD

**Issue by LouisonDVC** [LeeWannacott/table-sort-js#50]
When you sort the table, only the `<td>` elements are moved, not the `<tr>`. That could be ok, but the associated ids in the `<tr>` don't move either, making it difficult if we want to make further treatment on the table (changing data for example)

**Comment by LeeWannacott** [comment]
Duplicate of: https://github.com/LeeWannacott/table-sort-js/issues/88 fixed in https://github.com/LeeWannacott/table-sort-js/pull/89
