### ISSUE TITLE
Question: sort on a special row on loading site

### ISSUE THREAD

**Issue by nadjak77** [LeeWannacott/table-sort-js#52]
Hi,
I'm generating my table from database data. The data is fetched in several foreach loops. So I cannot sort my data by default.
Is there a option to use your sorting on loading the site? (like I am clicking on a tablehead)
Thank you.

**Comment by LeeWannacott** [comment]
Hey nadjak77,
Hard to say why it's not working without looking at the code. I would say just make sure the table is made before you call tableSortJS(), or source the script. Also, look at the examples in the docs and try and get one of them running first. You might be missing a `<thead>` or `<tbody>`. I don't think anyone has tried using table-sort-js with data coming from a database; I don't see why it wouldn't work though, you might need to use an async promise to load the data first and then make the table from it once you have retrieved the data. I don't know what technologies you are using; so it's hard to help.

These lines check if the page has completed loading, or if not uses an event listener to run it when it has loaded:
`if (
  document.readyState === "complete" ||
  document.readyState === "interactive"
) {
  tableSortJs();
} else if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", tableSortJs, false);
}`

I need to improve many things on this library. I have five weeks left on a coding boot-camp and then intend on improving it then. Thanks.

**Comment by s1de21** [comment]
Is there any new on this topic?

**Comment by LeeWannacott** [comment]
@s1de21 Can use "onload-sort" sort class I think this does what @nadjak77 was wanting simulates a click on a `<th>` from a user on page loaded.
