### ISSUE TITLE
Mixed positive and negative numbers don't sort correctly for "en-US" at least

### ISSUE THREAD

**Issue by CrozierSOS** [LeeWannacott/table-sort-js#64]
Hi! New to this project. Very nice and lightweight...thanks!

I notice that the list of numbers (3, -2, 1) sorts ascending as (1, -2, 3), rather than (-2, 1, 3) as I think would be more expected.

It looks like this is the result of including the `ignorePunctuation` parameter to `localeCompare`. Naively, if we just eliminated `ignorePunctuation`, it would work as expected, in at least this case. But I'm sure this was done for a reason. Can you let me know why so I can see if I can propose a solution?

Thanks again!

**Comment by LeeWannacott** [comment]
Hi @CrozierSOS 

I don't recall the rationale for `ignorePunctuation`. I would speculate it's for if you have numbers that are encased as a string `"1"`, or maybe if you have numbers that have a hashtag on the front `#1` , or perhaps encased/surrounded by parenthesis `(1)` (which is another way to show negative numbers (which currently also wont work with this library :sweat_smile:). These are just examples...etc

We should probably handle being able to have negative numbers though :sweat_smile: . I think the default should be to ignore punctuation :thinking:  and then have a boolean flag (className) for either negative numbers, or preferably not ignoring punctuation :thinking: . Or if you have a better solution, feel free to share.

Either way, I should probably have tests setup for ignoring punctuation and also for sorting negative numbers. I don't think negative numbers has ever come up, which is somewhat surprising; so thank you for raising it :+1: 

Cheers.

**Comment by CrozierSOS** [comment]
Thanks for the reply, @LeeWannacott 

I think you're probably right. Assuming the need for backward compatibility, making `ignorePunctuation: true` the default (as it is now) and allowing a `<table>` class like `ignore-punctuation-false` or `do-not-ignore-punctuation` would solve my problem...I *think*.

Would you like me to do a pull request for this?

Cheers!

**Comment by LeeWannacott** [comment]
Hey @CrozierSOS 

> allowing a `<table>` class like ignore-punctuation-false

I think it would be better to put the class on `<th>` (users might not want the functionality on all of the `<th>`) and naming it a double negative probably isn't the best (I know I suggested it); I think we could probably name it `sort-punctuation` (might be confusing for a developer, but should be more straight forward from a user perspective) and then mention that it allows sorting of negative numbers in the description...

> I think you're probably right. Assuming the need for backward compatibility

npm packages have versioning, so it's not the end of the world. However personally I find it annoying when libraries have a lot of churn.

> Would you like me to do a pull request for this?

Sure and if you need any help; feel free to ask.

Script: https://github.com/LeeWannacott/table-sort-js/blob/master/public/table-sort.js
Tests: https://github.com/LeeWannacott/table-sort-js/blob/master/test/table.test.js

Thanks.

**Comment by CrozierSOS** [comment]
Hi @LeeWannacott 

OK, so I gave this some more thought and tried out a few approaches. I don't think we can get the desired results using localeCompare, since it compares strings, so I took the approach of coercing the data to JavaScript Number values to sort. The whole concept of "punctuation" then is not relevant, so I landed on `bare-numbers` as an idea for the `th` class, but something else (`bare-number-sort`?) might be more consistent with existing classes. Let me know what you think about the approach, and I'll revise or add documentation and tests.

I don't do a lot of this, and none any more on GitHub, so I'm not sure I did things right, but I think you'll see it as a pull request to the main project, from my fork branch.

Thanks!

**Comment by LeeWannacott** [comment]
Hey @CrozierSOS  

Left some comments on the PR. https://github.com/LeeWannacott/table-sort-js/pull/65

I think in this case it might be a good idea and easier to write the tests first and then the solution; so you know if the test is handling edge cases, such as passing something to `Number()` that returns `NaN` (this is just an example) etc.

Cheers.

**Comment by LeeWannacott** [comment]
@CrozierSOS Done by [scodes73](https://github.com/scodes73) in PR https://github.com/LeeWannacott/table-sort-js/pull/87; release: 1.16.0 better late than never :sweat_smile: should infer the class automatically which is pretty cool. Still need to handle currency and percentages in numeric sort. https://github.com/LeeWannacott/table-sort-js/issues/97

**Comment by CrozierSOS** [comment]
@LeeWannacott Hi! FWIW, we decided to "fix" this issue by simply not including currency and other symbols in the actual cells. Instead we put a "legend" in the column header, like "Amount ($)".

**Comment by LeeWannacott** [comment]
> @LeeWannacott Hi! FWIW, we decided to "fix" this issue by simply not including currency and other symbols in the actual cells. Instead we put a "legend" in the column header, like "Amount ($)".

 Buffalo Springfield - For What It's Worth 1967 . That is one way to do it!, Shouldn't be too much work though to do currency as well; just need to modify the regex and strip the currency sign... famous last words...

p.s that reminds me I don't think this class handles number with commas in them; that's not ideal...

**Comment by CrozierSOS** [comment]
@LeeWannacott And handle multiple currencies....
