### ISSUE TITLE
Support multiple class for the table element

### ISSUE THREAD

**Issue by PierreR** [LeeWannacott/table-sort-js#8]
Most `table` elements will already have some class attached to it.

I would suggest to change the call to
        if (sortableTable.className === "table-sort") {
into
        if (sortableTable.classList.contains("table-sort")) {

Cheers

**Comment by LeeWannacott** [comment]
That is a good suggestion; if they are using Bootstrap, etc.

I was using this project to learn more about JavaScript; So I am sure their are some things I have overlooked.

Would you like to be assigned this issue and make a pull request?, or do you want me to change it?

Thank you.

**Comment by PierreR** [comment]
Up to you really. I won't make a PR with this because I have ended up using another simpler sorting algo.

Thanks for your quick feedback.

**Comment by LeeWannacott** [comment]
Okay no worries. Implemented in commit 17ee8df. Thanks for opening the issue.
