### ISSUE TITLE
sorting sorts cells, not rows

### ISSUE THREAD

**Issue by strager** [LeeWannacott/table-sort-js#88]
I have some row-specific `data-` attributes which I use in my JS code:
```html
<tr class="func" data-func-index="0">
<td>callee</td><td>0</td><td></td>
</tr>
<tr class="func" data-func-index="1">
<td>caller</td><td>72</td><td></td>
</tr>
<tr class="func" data-func-index="2">
<td>_DllMainCRTStartup</td><td>32</td><td></td>
</tr>
```

The data is attached to each `<tr>`. I have a click event listener on the entire table which finds the clicked `<tr>` and uses its `data-func-index` to show details.

table-sort-js breaks my table. When the user clicks on a column header, the data cells are sorted properly, but the `data-` attributes are not adjusted accordingly. `data-func-index="0"` should always be associated with the "callee" row, but after sorting by the second column (for example) it can be attached to a different row such as the "caller" row:
```html
<tr class="func" data-func-index="0">
<td>caller</td><td>72</td><td></td>
</tr>
<tr class="func" data-func-index="1">
<td>_DllMainCRTStartup</td><td>32</td><td></td>
</tr>
<tr class="func" data-func-index="2">
<td>callee</td><td>0</td><td></td>
</tr>
```

**Comment by LeeWannacott** [comment]
Fixed in: https://github.com/LeeWannacott/table-sort-js/compare/1.15...1.15.1

Still needs to be fixed for `file-size-sort`...

**Comment by LeeWannacott** [comment]
file-size-sort now sorts rows thanks to strager :1st_place_medal:  https://github.com/LeeWannacott/table-sort-js/pull/98

**Comment by LeeWannacott** [comment]
I added option https://github.com/LeeWannacott/table-sort-js/pull/108/files for cells-sort rather than tr
